#!/usr/bin/env python3
# Add a patient record to the database
# 
# usage: 
#    hrsdb_add_patient <first name> <second name> <gender> <dob>
#
# Example:
#   hrsdb_add_patient John Smith M 03/03/1993

import sys
import datetime

# Local imports
from hrsdb.db import DBHandler
from hrsdb.db.models import Patient

def parse_args():
    if len(sys.argv) < 5:
        print('Usage: hrsdb_add_patient <first name> <second name> <gender> <dob>')
        exit(1)

    # format date_of_birth
    print(sys.argv[4])
    dob = datetime.datetime.strptime(sys.argv[4], "%d/%m/%Y")

    # return dictionary
    return {
        'first_name'    : sys.argv[1],
        'last_name'     : sys.argv[2],
        'gender'        : int(sys.argv[3]),
        'date_of_birth' : dob
    }
        
def main():
    record = parse_args()

    with DBHandler() as dbhan:
        patient_record = Patient(**record)
        print(patient_record)

        dbhan.session.add(patient_record)
        dbhan.session.flush()
        dbhan.session.commit()

if __name__ == '__main__':
    main()
