#!/usr/bin/env python3
# HTTP web server

import argparse

# Local imports
from hrsdb.http.server import create_server


def parse_args():
    """Handle commandline flags"""
    parser = argparse.ArgumentParser()
    parser.add_argument('-p', '--port', type=int, default=8080, help='HTTP server port')
    parser.add_argument('-d', '--debug', action='store_true', help='Run the server in debug mode')
    return parser.parse_args()

def main():
    args = parse_args()
    app = create_server()
    app.run(port=args.port, debug=args.debug)
    

# Start main
if __name__ == '__main__':
    main()
